puts "The students of villains academy"
puts "--------------------------------"
puts "Dr. Hannibal Lector"
puts "Darth Vadar"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex Delarge"
puts "The Wicked witch of the south-west"
puts "Terminator"
puts "Freddy Krueger"
puts "Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
puts "Jason Vorhees"
puts "Michael Myers"